### ISSUE TITLE
repo-cooker reports success even if there was errors

### ISSUE THREAD

**Issue by Guria** [cerebral/repo-cooker#67]
Example log:
```
>npm run build

> overmind-monorepo@1.0.0 build C:\ws\cerebral\overmind
> repo-cooker --build

> babel-node --presets env C:/ws/cerebral/overmind/repo-cooker.js --build

npm
    run
    build
    {"cwd":"C:/ws/cerebral/overmind/packages/node_modules/action-chain"}
    OK

> action-chain@1.0.0-alpha1 prebuild C:\ws\cerebral\overmind\packages\node_modules\action-chain
> npm run clean



> action-chain@1.0.0-alpha1 clean C:\ws\cerebral\overmind\packages\node_modules\action-chain
> npx rimraf es lib coverage



> action-chain@1.0.0-alpha1 build C:\ws\cerebral\overmind\packages\node_modules\action-chain
> npm run build:lib & npm run build:es



> action-chain@1.0.0-alpha1 build:lib C:\ws\cerebral\overmind\packages\node_modules\action-chain
> tsc --outDir lib --module commonjs



> action-chain@1.0.0-alpha1 build:es C:\ws\cerebral\overmind\packages\node_modules\action-chain
> tsc --outDir es --module es2015



> action-chain@1.0.0-alpha1 postbuild C:\ws\cerebral\overmind\packages\node_modules\action-chain
> npx rimraf {lib,es}/**/__tests__



npm
    run
    build
    {"cwd":"C:/ws/cerebral/overmind/packages/node_modules/proxy-state-tree"}
    OK

> proxy-state-tree@1.0.0-beta4 prebuild C:\ws\cerebral\overmind\packages\node_modules\proxy-state-tree
> npm run clean



> proxy-state-tree@1.0.0-beta4 clean C:\ws\cerebral\overmind\packages\node_modules\proxy-state-tree
> npx rimraf es lib coverage



> proxy-state-tree@1.0.0-beta4 build C:\ws\cerebral\overmind\packages\node_modules\proxy-state-tree
> npm run build:lib & npm run build:es



> proxy-state-tree@1.0.0-beta4 build:lib C:\ws\cerebral\overmind\packages\node_modules\proxy-state-tree
> tsc --outDir lib --module commonjs



> proxy-state-tree@1.0.0-beta4 build:es C:\ws\cerebral\overmind\packages\node_modules\proxy-state-tree
> tsc --outDir es --module es2015



> proxy-state-tree@1.0.0-beta4 postbuild C:\ws\cerebral\overmind\packages\node_modules\proxy-state-tree
> npx rimraf {lib,es}/**/__tests__



npm
    run
    build
    {"cwd":"C:/ws/cerebral/overmind/packages/node_modules/overmind"}
    OK

> overmind@1.0.0-alpha1 prebuild C:\ws\cerebral\overmind\packages\node_modules\overmind
> npm run clean



> overmind@1.0.0-alpha1 clean C:\ws\cerebral\overmind\packages\node_modules\overmind
> npx rimraf es lib coverage



> overmind@1.0.0-alpha1 build C:\ws\cerebral\overmind\packages\node_modules\overmind
> npm run build:lib & npm run build:es



> overmind@1.0.0-alpha1 build:lib C:\ws\cerebral\overmind\packages\node_modules\overmind
> tsc --outDir lib --module commonjs



> overmind@1.0.0-alpha1 build:es C:\ws\cerebral\overmind\packages\node_modules\overmind
> tsc --outDir es --module es2015



> overmind@1.0.0-alpha1 postbuild C:\ws\cerebral\overmind\packages\node_modules\overmind
> npx rimraf {lib,es}/**/__tests__



npm
    run
    build
    {"cwd":"C:/ws/cerebral/overmind/packages/demos/todomvc"}
    FAIL

> todomvc@1.0.0-alpha1 build C:\ws\cerebral\overmind\packages\demos\todomvc
> webpack


module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\ws\cerebral\overmind\packages\demos\todomvc\node_modules\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm
 ERR! code ELIFECYCLE

npm
 ERR! errno
 1

npm
 ERR! todomvc@1.0.0-alpha1 build: `webpack`
npm ERR! Exit status 1

npm
 ERR!
npm ERR!
 Failed at the todomvc@1.0.0-alpha1 build script.

npm ERR!
 This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aleksei_Gurianov\AppData\Roaming\npm-cache\_logs\2018-07-17T11_35_20_884Z-debug.log


npm
    run
    build
    {"cwd":"C:/ws/cerebral/overmind/packages/node_modules/overmind-devtools"}
    OK

> overmind-devtools@1.0.0-alpha1 build C:\ws\cerebral\overmind\packages\node_modules\overmind-devtools
> npx webpack


Hash: 6b1f326f24b0ef10533c
Version: webpack 4.15.1
Time: 9584ms
Built at: 2018-07-17 15:35:31
     Asset       Size  Chunks             Chunk Names
 bundle.js   4.69 MiB    main  [emitted]  main
index.html  182 bytes          [emitted]
[../../../node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {main} [built]
[../overmind/es/index.js] 4.11 KiB {main} [built]
[../overmind/es/views/react.js] 5.86 KiB {main} [built]
[./src/client/BackendConnector.ts] 2.78 KiB {main} [built]
[./src/client/app/actions.ts] 1.68 KiB {main} [built]
[./src/client/app/helpers.ts] 821 bytes {main} [built]
[./src/client/app/index.ts] 416 bytes {main} [built]
[./src/client/app/mutations.ts] 3.82 KiB {main} [built]
[./src/client/app/providers.ts] 1.86 KiB {main} [built]
[./src/client/app/state.ts] 467 bytes {main} [built]
[./src/client/icomoon.woff2] 1.38 KiB {main} [built]
[./src/client/index.tsx] 1.57 KiB {main} [built]
[./src/client/styled-components.ts] 436 bytes {main} [built]
[./src/client/theme.ts] 945 bytes {main} [built]
[stream] external "stream" 42 bytes {main} [built]
    + 109 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    [../../../node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 2 hidden modules


***********************
**                   **
** build: SUCCESS !! **
**                   **
***********************

```

**Comment by Guria** [comment]
seems to be fixed
